// ============================================================
// balco.nyc — the city-of-blocks hero.
//
// Every square is a block of the five boroughs, rasterised from the city's
// published borough boundaries. Each takes one of five shades of the brand
// red depending on how far it sits from the sun, and the sun follows the
// cursor across the sky. The map is north-up, so the right side is east and
// morning, the left is west and evening.
//
// The shading is light, not data: it is the sun's position, not any block's
// modelled output. Generated by design/home-directions/build_sunwhite.py.
// ============================================================
(function () {
  var COLS = 36, ROWS = 36, PITCH = 10, BLOCK = 8.6;
  var VW = 360, VH = 360;
  var SHADES = ["#E46740", "#C2452A", "#A85643", "#C8A9A1", "#D2C3BF"];
  var RADII = [187, 270, 367, 475, 616, 781];
  var BOUNDS = [0.24, 0.43, 0.64, 0.9];
  var CELLS = [[22,0,3],[23,0,0],[22,1,2],[23,1,4],[24,1,3],[25,1,0],[26,1,3],[22,2,1],[23,2,4],[24,2,1],[25,2,3],[26,2,3],[27,2,0],[28,2,2],[21,3,3],[22,3,4],[23,3,1],[24,3,0],[25,3,3],[26,3,1],[27,3,2],[28,3,3],[29,3,0],[21,4,2],[22,4,1],[23,4,2],[24,4,4],[25,4,1],[26,4,0],[27,4,4],[28,4,2],[29,4,2],[20,5,4],[21,5,2],[22,5,0],[23,5,1],[24,5,2],[25,5,2],[26,5,4],[27,5,2],[29,5,5],[30,5,4],[31,5,2],[20,6,1],[21,6,0],[22,6,4],[23,6,3],[24,6,0],[25,6,2],[26,6,3],[27,6,3],[28,6,4],[30,6,0],[19,7,4],[20,7,0],[21,7,2],[22,7,2],[23,7,0],[24,7,4],[25,7,4],[26,7,1],[27,7,2],[28,7,4],[19,8,0],[20,8,1],[21,8,5],[22,8,1],[23,8,2],[24,8,3],[25,8,2],[26,8,5],[27,8,4],[28,8,1],[29,8,2],[18,9,3],[19,9,1],[20,9,3],[21,9,1],[22,9,1],[24,9,2],[18,10,0],[19,10,3],[20,10,4],[21,10,2],[24,10,2],[26,10,3],[28,10,3],[29,10,2],[17,11,2],[18,11,4],[19,11,2],[22,11,5],[23,11,2],[24,11,3],[26,11,1],[27,11,5],[28,11,2],[29,11,0],[30,11,3],[17,12,2],[18,12,4],[19,12,3],[21,12,3],[22,12,1],[23,12,3],[24,12,5],[25,12,1],[26,12,1],[27,12,2],[28,12,0],[29,12,4],[30,12,2],[31,12,0],[32,12,3],[33,12,3],[16,13,3],[17,13,5],[18,13,0],[19,13,2],[20,13,5],[21,13,3],[22,13,3],[23,13,2],[24,13,1],[25,13,2],[26,13,4],[27,13,0],[28,13,0],[29,13,3],[30,13,0],[31,13,4],[32,13,3],[33,13,0],[34,13,3],[16,14,4],[17,14,3],[18,14,3],[19,14,5],[20,14,1],[21,14,2],[22,14,4],[23,14,2],[24,14,2],[25,14,2],[26,14,0],[27,14,2],[28,14,4],[29,14,1],[30,14,0],[31,14,4],[32,14,2],[33,14,4],[34,14,4],[35,14,0],[16,15,4],[17,15,0],[19,15,3],[20,15,2],[21,15,4],[22,15,0],[23,15,0],[24,15,4],[25,15,2],[26,15,1],[27,15,2],[28,15,1],[29,15,2],[30,15,5],[31,15,2],[32,15,1],[33,15,5],[34,15,3],[35,15,3],[16,16,2],[17,16,5],[19,16,0],[20,16,3],[21,16,3],[22,16,1],[23,16,3],[24,16,0],[25,16,0],[26,16,4],[27,16,3],[28,16,1],[29,16,2],[30,16,3],[31,16,3],[32,16,5],[33,16,3],[15,17,2],[16,17,2],[17,17,3],[19,17,3],[20,17,3],[21,17,0],[22,17,2],[23,17,3],[24,17,1],[25,17,3],[26,17,1],[27,17,1],[28,17,5],[29,17,4],[30,17,2],[31,17,3],[32,17,3],[33,17,3],[17,18,1],[18,18,1],[19,18,2],[20,18,2],[21,18,2],[22,18,3],[23,18,0],[24,18,2],[25,18,5],[26,18,1],[27,18,3],[28,18,3],[29,18,1],[30,18,5],[31,18,4],[32,18,1],[33,18,2],[15,19,3],[16,19,0],[17,19,3],[18,19,4],[19,19,1],[20,19,0],[21,19,2],[22,19,2],[23,19,2],[24,19,4],[25,19,0],[26,19,2],[27,19,5],[28,19,2],[29,19,3],[30,19,3],[31,19,1],[32,19,4],[33,19,3],[15,20,3],[16,20,0],[17,20,2],[18,20,0],[19,20,2],[20,20,4],[21,20,1],[22,20,1],[23,20,3],[24,20,4],[25,20,3],[26,20,4],[27,20,1],[28,20,2],[29,20,5],[30,20,2],[31,20,1],[32,20,2],[33,20,0],[17,21,3],[18,21,0],[19,21,2],[20,21,1],[21,21,2],[22,21,5],[23,21,2],[24,21,1],[25,21,4],[26,21,4],[27,21,2],[28,21,4],[29,21,1],[30,21,1],[31,21,5],[32,21,1],[33,21,0],[15,22,1],[16,22,2],[17,22,0],[18,22,4],[19,22,4],[20,22,0],[21,22,3],[22,22,3],[23,22,3],[24,22,5],[25,22,3],[26,22,1],[28,22,4],[29,22,1],[30,22,2],[31,22,1],[32,22,0],[33,22,5],[4,23,1],[5,23,3],[7,23,1],[9,23,3],[10,23,1],[11,23,3],[14,23,1],[15,23,4],[16,23,2],[17,23,1],[18,23,3],[19,23,1],[20,23,4],[21,23,5],[22,23,1],[23,23,3],[24,23,3],[29,23,2],[30,23,4],[31,23,0],[32,23,2],[4,24,2],[5,24,4],[6,24,2],[7,24,2],[8,24,5],[9,24,1],[10,24,0],[11,24,3],[14,24,2],[15,24,0],[16,24,1],[17,24,5],[18,24,3],[19,24,2],[20,24,4],[21,24,2],[22,24,4],[23,24,5],[27,24,2],[28,24,3],[31,24,2],[4,25,4],[5,25,4],[6,25,1],[7,25,2],[8,25,2],[9,25,1],[10,25,5],[11,25,1],[14,25,2],[15,25,3],[16,25,3],[17,25,1],[18,25,2],[19,25,5],[20,25,3],[21,25,1],[24,25,3],[27,25,1],[30,25,2],[31,25,2],[3,26,4],[4,26,2],[5,26,1],[6,26,3],[7,26,4],[8,26,0],[9,26,1],[10,26,2],[11,26,1],[12,26,4],[15,26,4],[16,26,3],[17,26,3],[18,26,3],[19,26,2],[20,26,2],[21,26,5],[26,26,1],[29,26,1],[31,26,3],[32,26,3],[4,27,2],[5,27,2],[6,27,1],[7,27,0],[8,27,3],[9,27,4],[10,27,0],[11,27,1],[12,27,3],[16,27,0],[17,27,4],[18,27,4],[19,27,2],[20,27,3],[21,27,2],[22,27,1],[23,27,4],[29,27,4],[30,27,1],[31,27,1],[32,27,5],[3,28,0],[4,28,2],[5,28,4],[6,28,1],[7,28,1],[8,28,1],[9,28,1],[10,28,3],[11,28,5],[17,28,3],[18,28,0],[19,28,4],[23,28,1],[27,28,0],[3,29,2],[4,29,3],[5,29,0],[6,29,1],[7,29,4],[8,29,2],[9,29,1],[10,29,2],[25,29,2],[3,30,3],[4,30,2],[5,30,1],[6,30,3],[7,30,0],[8,30,2],[9,30,5],[21,30,2],[22,30,0],[23,30,2],[1,31,1],[2,31,3],[3,31,2],[4,31,0],[5,31,3],[6,31,4],[7,31,1],[8,31,4],[20,31,4],[1,32,1],[2,32,2],[3,32,2],[4,32,3],[5,32,3],[6,32,0],[7,32,4],[1,33,3],[2,33,0],[3,33,1],[4,33,3],[5,33,3],[0,34,2],[1,34,1],[2,34,3],[0,35,2]];

  var host = document.getElementById('heroCity');
  if (!host) return;

  var NS = 'http://www.w3.org/2000/svg';
  var svg = document.createElementNS(NS, 'svg');
  svg.setAttribute('viewBox', '0 0 ' + VW + ' ' + VH);
  svg.setAttribute('width', '100%');
  svg.setAttribute('height', '100%');
  svg.setAttribute('preserveAspectRatio', 'xMidYMid meet');
  svg.setAttribute('shape-rendering', 'crispEdges');
  svg.setAttribute('aria-hidden', 'true');

  var blocks = [];
  for (var n = 0; n < CELLS.length; n++) {
    var c = CELLS[n];
    var r = document.createElementNS(NS, 'rect');
    r.setAttribute('x', c[0] * PITCH);
    r.setAttribute('y', c[1] * PITCH);
    r.setAttribute('width', BLOCK);
    r.setAttribute('height', BLOCK);
    r.setAttribute('fill', SHADES[SHADES.length - 1]);
    svg.appendChild(r);
    blocks.push({ el: r, band: -1,
      x: c[0] * PITCH + BLOCK / 2, y: c[1] * PITCH + BLOCK / 2, r: RADII[c[2]] });
  }
  host.appendChild(svg);

  var sun = document.getElementById('heroSun');
  var halo = document.getElementById('heroHalo');
  var clock = document.getElementById('heroClock');
  var hero = document.getElementById('heroSection');
  var reduced = window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches;

  var t = 0.46, target = 0.46, phase = Math.asin((0.46 - 0.5) / 0.46);
  var idle = true, lastMove = 0, frame = null;

  if (hero) {
    hero.addEventListener('mousemove', function (e) {
      var box = hero.getBoundingClientRect();
      if (!box.width) return;
      target = Math.max(0, Math.min(1, (e.clientX - box.left) / box.width));
      idle = false; lastMove = Date.now();
    });
    hero.addEventListener('mouseleave', function () { lastMove = Date.now(); });
  }

  function paint() {
    var box = host.getBoundingClientRect();
    if (!box.width) return;
    // The sun rides a shallow arc across the top of the map, in the map's own
    // coordinates. It stays inside the frame so it never collides with the nav.
    var ax = 0.30 + t * 0.58;
    var ay = 0.020 + 0.062 * (1 - Math.sqrt(Math.max(0, 1 - Math.pow(2 * t - 1, 2))));
    var sx = ax * VW, sy = ay * VH;
    for (var i = 0; i < blocks.length; i++) {
      var b = blocks[i];
      var dx = b.x - sx, dy = b.y - sy;
      var d = Math.sqrt(dx * dx + dy * dy) / b.r;
      var band = 0;
      while (band < BOUNDS.length && d >= BOUNDS[band]) band++;
      if (band !== b.band) { b.band = band; b.el.setAttribute('fill', SHADES[band]); }
    }
    if (sun) {
      var px = box.left + ax * box.width, py = box.top + ay * box.height;
      var hostBox = host.offsetParent ? host.offsetParent.getBoundingClientRect() : box;
      sun.style.left = (px - hostBox.left) + 'px';
      sun.style.top = (py - hostBox.top) + 'px';
      if (halo) { halo.style.left = sun.style.left; halo.style.top = sun.style.top; }
    }
    if (clock) {
      var mins = Math.round((18 - t * 12) * 60);
      var h = Math.floor(mins / 60), m = mins % 60;
      clock.textContent = (h % 12 || 12) + ':' + (m < 10 ? '0' + m : m) + ' ' + (h >= 12 ? 'PM' : 'AM');
    }
  }

  function tick() {
    frame = requestAnimationFrame(tick);
    if (!idle && Date.now() - lastMove > 2400) idle = true;
    if (idle && !reduced) { phase += 0.0021; target = 0.5 + 0.46 * Math.sin(phase); }
    t += (target - t) * 0.09;
    paint();
  }

  paint();
  if (!reduced) tick(); else paint();

  // the scene takes over once an address resolves; stop burning frames then
  window.addEventListener('balco:sceneopen', function () {
    if (frame) { cancelAnimationFrame(frame); frame = null; }
  });
  window.addEventListener('balco:scenereset', function () {
    if (!frame && !reduced) tick();
  });
})();
